version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    CLUSTER_NAME: my-cluster        # <-- updated to your actual cluster
    HELM_RELEASE: myapp

phases:
  pre_build:
    commands:
      - echo Login to ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 113461832962.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=113461832962.dkr.ecr.$AWS_REGION.amazonaws.com/alikha-codebuild
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - docker build -t app:$IMAGE_TAG .
      - docker tag app:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - helm upgrade --install $HELM_RELEASE ./helm/myapp \
          --set image.repository=$REPOSITORY_URI \
          --set image.tag=$IMAGE_TAG
